version: '3.7'

services:
  database:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=rpi1234
    volumes:
      - local-volume:/data/postgres

volumes:
  local-volume:
    driver: local